[package]
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"
name = "the-caretaker"
version = "0.1.0"

[dependencies]
anyhow = "1.0.33"
chrono = "0.4.19"
diesel = {version = "1.4.5", features = ["postgres"]}
dotenv = "0.15.0"
envy = "0.4.1"
fern = "0.6.0"
log = "0.4.11"
serde = {version = "1.0.116", features = ["derive"]}
serenity = "0.9.0-rc.2"
structopt = {version = "0.3.20", default-features = false}
strum = {version = "0.19.5", features = ["derive"]}
thiserror = "1.0.21"
tokio = {version = "0.2.22", features = ["macros"]}
