---
version: '3.8'
services:
  psql:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: caretaker
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db:
